// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package translator

import (
	"context"
	"net/url"

	mock "github.com/stretchr/testify/mock"
	"github.com/trezorg/lingualeo/internal/api"
)

// NewMock_Downloader creates a new instance of Mock_Downloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_Downloader(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_Downloader {
	mock := &Mock_Downloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mock_Downloader is an autogenerated mock type for the Downloader type
type Mock_Downloader struct {
	mock.Mock
}

type Mock_Downloader_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_Downloader) EXPECT() *Mock_Downloader_Expecter {
	return &Mock_Downloader_Expecter{mock: &_m.Mock}
}

// Download provides a mock function for the type Mock_Downloader
func (_mock *Mock_Downloader) Download(url string) (string, error) {
	ret := _mock.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(url)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(url)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mock_Downloader_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type Mock_Downloader_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - url string
func (_e *Mock_Downloader_Expecter) Download(url interface{}) *Mock_Downloader_Download_Call {
	return &Mock_Downloader_Download_Call{Call: _e.mock.On("Download", url)}
}

func (_c *Mock_Downloader_Download_Call) Run(run func(url string)) *Mock_Downloader_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Mock_Downloader_Download_Call) Return(s string, err error) *Mock_Downloader_Download_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Mock_Downloader_Download_Call) RunAndReturn(run func(url string) (string, error)) *Mock_Downloader_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type Mock_Downloader
func (_mock *Mock_Downloader) Remove(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Mock_Downloader_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type Mock_Downloader_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - path string
func (_e *Mock_Downloader_Expecter) Remove(path interface{}) *Mock_Downloader_Remove_Call {
	return &Mock_Downloader_Remove_Call{Call: _e.mock.On("Remove", path)}
}

func (_c *Mock_Downloader_Remove_Call) Run(run func(path string)) *Mock_Downloader_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Mock_Downloader_Remove_Call) Return(err error) *Mock_Downloader_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Mock_Downloader_Remove_Call) RunAndReturn(run func(path string) error) *Mock_Downloader_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// NewMock_Translator creates a new instance of Mock_Translator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_Translator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_Translator {
	mock := &Mock_Translator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mock_Translator is an autogenerated mock type for the Translator type
type Mock_Translator struct {
	mock.Mock
}

type Mock_Translator_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_Translator) EXPECT() *Mock_Translator_Expecter {
	return &Mock_Translator_Expecter{mock: &_m.Mock}
}

// AddWord provides a mock function for the type Mock_Translator
func (_mock *Mock_Translator) AddWord(word string, translate string) api.OperationResult {
	ret := _mock.Called(word, translate)

	if len(ret) == 0 {
		panic("no return value specified for AddWord")
	}

	var r0 api.OperationResult
	if returnFunc, ok := ret.Get(0).(func(string, string) api.OperationResult); ok {
		r0 = returnFunc(word, translate)
	} else {
		r0 = ret.Get(0).(api.OperationResult)
	}
	return r0
}

// Mock_Translator_AddWord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWord'
type Mock_Translator_AddWord_Call struct {
	*mock.Call
}

// AddWord is a helper method to define mock.On call
//   - word string
//   - translate string
func (_e *Mock_Translator_Expecter) AddWord(word interface{}, translate interface{}) *Mock_Translator_AddWord_Call {
	return &Mock_Translator_AddWord_Call{Call: _e.mock.On("AddWord", word, translate)}
}

func (_c *Mock_Translator_AddWord_Call) Run(run func(word string, translate string)) *Mock_Translator_AddWord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mock_Translator_AddWord_Call) Return(operationResult api.OperationResult) *Mock_Translator_AddWord_Call {
	_c.Call.Return(operationResult)
	return _c
}

func (_c *Mock_Translator_AddWord_Call) RunAndReturn(run func(word string, translate string) api.OperationResult) *Mock_Translator_AddWord_Call {
	_c.Call.Return(run)
	return _c
}

// TranslateWord provides a mock function for the type Mock_Translator
func (_mock *Mock_Translator) TranslateWord(word string) api.OperationResult {
	ret := _mock.Called(word)

	if len(ret) == 0 {
		panic("no return value specified for TranslateWord")
	}

	var r0 api.OperationResult
	if returnFunc, ok := ret.Get(0).(func(string) api.OperationResult); ok {
		r0 = returnFunc(word)
	} else {
		r0 = ret.Get(0).(api.OperationResult)
	}
	return r0
}

// Mock_Translator_TranslateWord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TranslateWord'
type Mock_Translator_TranslateWord_Call struct {
	*mock.Call
}

// TranslateWord is a helper method to define mock.On call
//   - word string
func (_e *Mock_Translator_Expecter) TranslateWord(word interface{}) *Mock_Translator_TranslateWord_Call {
	return &Mock_Translator_TranslateWord_Call{Call: _e.mock.On("TranslateWord", word)}
}

func (_c *Mock_Translator_TranslateWord_Call) Run(run func(word string)) *Mock_Translator_TranslateWord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Mock_Translator_TranslateWord_Call) Return(operationResult api.OperationResult) *Mock_Translator_TranslateWord_Call {
	_c.Call.Return(operationResult)
	return _c
}

func (_c *Mock_Translator_TranslateWord_Call) RunAndReturn(run func(word string) api.OperationResult) *Mock_Translator_TranslateWord_Call {
	_c.Call.Return(run)
	return _c
}

// NewMock_Outputer creates a new instance of Mock_Outputer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_Outputer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_Outputer {
	mock := &Mock_Outputer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mock_Outputer is an autogenerated mock type for the Outputer type
type Mock_Outputer struct {
	mock.Mock
}

type Mock_Outputer_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_Outputer) EXPECT() *Mock_Outputer_Expecter {
	return &Mock_Outputer_Expecter{mock: &_m.Mock}
}

// Output provides a mock function for the type Mock_Outputer
func (_mock *Mock_Outputer) Output(ctx context.Context, r api.Result) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Output")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, api.Result) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Mock_Outputer_Output_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Output'
type Mock_Outputer_Output_Call struct {
	*mock.Call
}

// Output is a helper method to define mock.On call
//   - ctx context.Context
//   - r api.Result
func (_e *Mock_Outputer_Expecter) Output(ctx interface{}, r interface{}) *Mock_Outputer_Output_Call {
	return &Mock_Outputer_Output_Call{Call: _e.mock.On("Output", ctx, r)}
}

func (_c *Mock_Outputer_Output_Call) Run(run func(ctx context.Context, r api.Result)) *Mock_Outputer_Output_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 api.Result
		if args[1] != nil {
			arg1 = args[1].(api.Result)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mock_Outputer_Output_Call) Return(err error) *Mock_Outputer_Output_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Mock_Outputer_Output_Call) RunAndReturn(run func(ctx context.Context, r api.Result) error) *Mock_Outputer_Output_Call {
	_c.Call.Return(run)
	return _c
}

// NewMock_Pronouncer creates a new instance of Mock_Pronouncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_Pronouncer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_Pronouncer {
	mock := &Mock_Pronouncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mock_Pronouncer is an autogenerated mock type for the Pronouncer type
type Mock_Pronouncer struct {
	mock.Mock
}

type Mock_Pronouncer_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_Pronouncer) EXPECT() *Mock_Pronouncer_Expecter {
	return &Mock_Pronouncer_Expecter{mock: &_m.Mock}
}

// Play provides a mock function for the type Mock_Pronouncer
func (_mock *Mock_Pronouncer) Play(ctx context.Context, url string) error {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Play")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, url)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Mock_Pronouncer_Play_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Play'
type Mock_Pronouncer_Play_Call struct {
	*mock.Call
}

// Play is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *Mock_Pronouncer_Expecter) Play(ctx interface{}, url interface{}) *Mock_Pronouncer_Play_Call {
	return &Mock_Pronouncer_Play_Call{Call: _e.mock.On("Play", ctx, url)}
}

func (_c *Mock_Pronouncer_Play_Call) Run(run func(ctx context.Context, url string)) *Mock_Pronouncer_Play_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mock_Pronouncer_Play_Call) Return(err error) *Mock_Pronouncer_Play_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Mock_Pronouncer_Play_Call) RunAndReturn(run func(ctx context.Context, url string) error) *Mock_Pronouncer_Play_Call {
	_c.Call.Return(run)
	return _c
}

// NewMock_Visualizer creates a new instance of Mock_Visualizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_Visualizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_Visualizer {
	mock := &Mock_Visualizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mock_Visualizer is an autogenerated mock type for the Visualizer type
type Mock_Visualizer struct {
	mock.Mock
}

type Mock_Visualizer_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_Visualizer) EXPECT() *Mock_Visualizer_Expecter {
	return &Mock_Visualizer_Expecter{mock: &_m.Mock}
}

// Show provides a mock function for the type Mock_Visualizer
func (_mock *Mock_Visualizer) Show(u *url.URL) error {
	ret := _mock.Called(u)

	if len(ret) == 0 {
		panic("no return value specified for Show")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*url.URL) error); ok {
		r0 = returnFunc(u)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Mock_Visualizer_Show_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Show'
type Mock_Visualizer_Show_Call struct {
	*mock.Call
}

// Show is a helper method to define mock.On call
//   - u *url.URL
func (_e *Mock_Visualizer_Expecter) Show(u interface{}) *Mock_Visualizer_Show_Call {
	return &Mock_Visualizer_Show_Call{Call: _e.mock.On("Show", u)}
}

func (_c *Mock_Visualizer_Show_Call) Run(run func(u *url.URL)) *Mock_Visualizer_Show_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *url.URL
		if args[0] != nil {
			arg0 = args[0].(*url.URL)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Mock_Visualizer_Show_Call) Return(err error) *Mock_Visualizer_Show_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Mock_Visualizer_Show_Call) RunAndReturn(run func(u *url.URL) error) *Mock_Visualizer_Show_Call {
	_c.Call.Return(run)
	return _c
}
