// Code generated by mockery v2.43.0. DO NOT EDIT.

package translator

import (
	context "context"

	api "github.com/trezorg/lingualeo/pkg/api"

	mock "github.com/stretchr/testify/mock"
)

// Mock_Outputer is an autogenerated mock type for the Outputer type
type Mock_Outputer struct {
	mock.Mock
}

type Mock_Outputer_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_Outputer) EXPECT() *Mock_Outputer_Expecter {
	return &Mock_Outputer_Expecter{mock: &_m.Mock}
}

// Output provides a mock function with given fields: ctx, r
func (_m *Mock_Outputer) Output(ctx context.Context, r api.Result) error {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Output")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, api.Result) error); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mock_Outputer_Output_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Output'
type Mock_Outputer_Output_Call struct {
	*mock.Call
}

// Output is a helper method to define mock.On call
//   - ctx context.Context
//   - r api.Result
func (_e *Mock_Outputer_Expecter) Output(ctx interface{}, r interface{}) *Mock_Outputer_Output_Call {
	return &Mock_Outputer_Output_Call{Call: _e.mock.On("Output", ctx, r)}
}

func (_c *Mock_Outputer_Output_Call) Run(run func(ctx context.Context, r api.Result)) *Mock_Outputer_Output_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(api.Result))
	})
	return _c
}

func (_c *Mock_Outputer_Output_Call) Return(_a0 error) *Mock_Outputer_Output_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mock_Outputer_Output_Call) RunAndReturn(run func(context.Context, api.Result) error) *Mock_Outputer_Output_Call {
	_c.Call.Return(run)
	return _c
}

// NewMock_Outputer creates a new instance of Mock_Outputer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_Outputer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_Outputer {
	mock := &Mock_Outputer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
