// Code generated by mockery v2.43.0. DO NOT EDIT.

package translator

import mock "github.com/stretchr/testify/mock"

// Mock_Option is an autogenerated mock type for the Option type
type Mock_Option struct {
	mock.Mock
}

type Mock_Option_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_Option) EXPECT() *Mock_Option_Expecter {
	return &Mock_Option_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *Mock_Option) Execute(_a0 *Lingualeo) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*Lingualeo) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mock_Option_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type Mock_Option_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *Lingualeo
func (_e *Mock_Option_Expecter) Execute(_a0 interface{}) *Mock_Option_Execute_Call {
	return &Mock_Option_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *Mock_Option_Execute_Call) Run(run func(_a0 *Lingualeo)) *Mock_Option_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*Lingualeo))
	})
	return _c
}

func (_c *Mock_Option_Execute_Call) Return(_a0 error) *Mock_Option_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mock_Option_Execute_Call) RunAndReturn(run func(*Lingualeo) error) *Mock_Option_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMock_Option creates a new instance of Mock_Option. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_Option(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_Option {
	mock := &Mock_Option{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
