// Code generated by mockery v2.43.0. DO NOT EDIT.

package translator

import (
	mock "github.com/stretchr/testify/mock"
	api "github.com/trezorg/lingualeo/pkg/api"
)

// Mock_processResult is an autogenerated mock type for the processResult type
type Mock_processResult struct {
	mock.Mock
}

type Mock_processResult_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_processResult) EXPECT() *Mock_processResult_Expecter {
	return &Mock_processResult_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *Mock_processResult) Execute(_a0 api.Result) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(api.Result) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mock_processResult_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type Mock_processResult_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 api.Result
func (_e *Mock_processResult_Expecter) Execute(_a0 interface{}) *Mock_processResult_Execute_Call {
	return &Mock_processResult_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *Mock_processResult_Execute_Call) Run(run func(_a0 api.Result)) *Mock_processResult_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(api.Result))
	})
	return _c
}

func (_c *Mock_processResult_Execute_Call) Return(_a0 error) *Mock_processResult_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mock_processResult_Execute_Call) RunAndReturn(run func(api.Result) error) *Mock_processResult_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMock_processResult creates a new instance of Mock_processResult. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_processResult(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_processResult {
	mock := &Mock_processResult{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
