version: 2

before:
  hooks:
    - make tidy generate

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    main: ./cmd/lingualeo

archives:
  - formats:
      - binary
    name_template: >-
      {{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if eq .Os "windows" }}.exe{{ end }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch

sboms:
  - artifacts: binary

release:
  github:
    owner: trezorg
    name: lingualeo
  draft: false
  prerelease: auto
  mode: replace
