// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/trezorg/lingualeo/internal/api"
)

// NewMock_Client creates a new instance of Mock_Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_Client {
	mock := &Mock_Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mock_Client is an autogenerated mock type for the Client type
type Mock_Client struct {
	mock.Mock
}

type Mock_Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_Client) EXPECT() *Mock_Client_Expecter {
	return &Mock_Client_Expecter{mock: &_m.Mock}
}

// AddWord provides a mock function for the type Mock_Client
func (_mock *Mock_Client) AddWord(ctx context.Context, word string, translate string) api.OperationResult {
	ret := _mock.Called(ctx, word, translate)

	if len(ret) == 0 {
		panic("no return value specified for AddWord")
	}

	var r0 api.OperationResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) api.OperationResult); ok {
		r0 = returnFunc(ctx, word, translate)
	} else {
		r0 = ret.Get(0).(api.OperationResult)
	}
	return r0
}

// Mock_Client_AddWord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWord'
type Mock_Client_AddWord_Call struct {
	*mock.Call
}

// AddWord is a helper method to define mock.On call
//   - ctx context.Context
//   - word string
//   - translate string
func (_e *Mock_Client_Expecter) AddWord(ctx interface{}, word interface{}, translate interface{}) *Mock_Client_AddWord_Call {
	return &Mock_Client_AddWord_Call{Call: _e.mock.On("AddWord", ctx, word, translate)}
}

func (_c *Mock_Client_AddWord_Call) Run(run func(ctx context.Context, word string, translate string)) *Mock_Client_AddWord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Mock_Client_AddWord_Call) Return(operationResult api.OperationResult) *Mock_Client_AddWord_Call {
	_c.Call.Return(operationResult)
	return _c
}

func (_c *Mock_Client_AddWord_Call) RunAndReturn(run func(ctx context.Context, word string, translate string) api.OperationResult) *Mock_Client_AddWord_Call {
	_c.Call.Return(run)
	return _c
}

// TranslateWord provides a mock function for the type Mock_Client
func (_mock *Mock_Client) TranslateWord(ctx context.Context, word string) api.OperationResult {
	ret := _mock.Called(ctx, word)

	if len(ret) == 0 {
		panic("no return value specified for TranslateWord")
	}

	var r0 api.OperationResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) api.OperationResult); ok {
		r0 = returnFunc(ctx, word)
	} else {
		r0 = ret.Get(0).(api.OperationResult)
	}
	return r0
}

// Mock_Client_TranslateWord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TranslateWord'
type Mock_Client_TranslateWord_Call struct {
	*mock.Call
}

// TranslateWord is a helper method to define mock.On call
//   - ctx context.Context
//   - word string
func (_e *Mock_Client_Expecter) TranslateWord(ctx interface{}, word interface{}) *Mock_Client_TranslateWord_Call {
	return &Mock_Client_TranslateWord_Call{Call: _e.mock.On("TranslateWord", ctx, word)}
}

func (_c *Mock_Client_TranslateWord_Call) Run(run func(ctx context.Context, word string)) *Mock_Client_TranslateWord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mock_Client_TranslateWord_Call) Return(operationResult api.OperationResult) *Mock_Client_TranslateWord_Call {
	_c.Call.Return(operationResult)
	return _c
}

func (_c *Mock_Client_TranslateWord_Call) RunAndReturn(run func(ctx context.Context, word string) api.OperationResult) *Mock_Client_TranslateWord_Call {
	_c.Call.Return(run)
	return _c
}
